// <auto-generated />
using System;
using Foyer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Foyer.Migrations
{
    [DbContext(typeof(FoyerContext))]
    partial class FoyerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "frequency", new[] { "daily", "monthly", "never", "weekly", "yearly" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Foyer.Models.DoneTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DoneDate")
                        .HasColumnType("date")
                        .HasColumnName("done_date");

                    b.Property<int>("TaskId")
                        .HasColumnType("integer")
                        .HasColumnName("task_id");

                    b.HasKey("Id")
                        .HasName("pk_done_tasks");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_done_tasks_task_id");

                    b.ToTable("done_tasks", (string)null);
                });

            modelBuilder.Entity("Foyer.Models.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Frequency>("Frequency")
                        .HasColumnType("frequency")
                        .HasColumnName("frequency");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_tasks");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("Foyer.Models.DoneTask", b =>
                {
                    b.HasOne("Foyer.Models.Task", "Task")
                        .WithMany("DoneTasks")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_done_tasks_tasks_task_id");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Foyer.Models.Task", b =>
                {
                    b.OwnsOne("Foyer.Models.Meta", "Meta", b1 =>
                        {
                            b1.Property<int>("TaskId")
                                .HasColumnType("integer");

                            b1.Property<int?>("DayOfWeek")
                                .HasColumnType("integer");

                            b1.PrimitiveCollection<int[]>("DaysOfWeek")
                                .HasColumnType("integer[]");

                            b1.Property<int?>("Each")
                                .HasColumnType("integer");

                            b1.Property<int>("Interval")
                                .HasColumnType("integer");

                            b1.Property<int?>("Week")
                                .HasColumnType("integer");

                            b1.HasKey("TaskId");

                            b1.ToTable("tasks");

                            b1.ToJson("meta");

                            b1.WithOwner()
                                .HasForeignKey("TaskId")
                                .HasConstraintName("fk_tasks_tasks_id");
                        });

                    b.Navigation("Meta");
                });

            modelBuilder.Entity("Foyer.Models.Task", b =>
                {
                    b.Navigation("DoneTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
